name: Coach Barrow
favicon: null
layout_spectrum: 0.0073
typography_spectrum: 0.3128944009076804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5177485225722194
  lightness: 0.8593869241885841
  saturation: 0.5037234951741993
  rhythmicContrast: 0.7726437179371715
purpose: []
