name: Coach Barrow
favicon: null
layout_spectrum: 0.0073
typography_spectrum: 0.2862513
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42311f'
    - '#111305'
    - '#9e7865'
    - '#725c44'
    - '#b58f82'
  brandStrength: 0.5177485225722194
  lightness: 0.8593869241885841
  saturation: 0.5037234951741993
  rhythmicContrast: 0.7726437179371715
purpose: []
